plugins {
    id("java")
    id("com.gradleup.shadow") version "9.3.1"
}

group = "me.needkg.daynightpvp"
version = "2.0.0"

repositories {
    mavenCentral()

    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT")
    implementation("org.bstats:bstats-bukkit:3.2.1")
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

processResources {
    def props = [version: rootProject.version]
    inputs.properties props
    filteringCharset 'UTF-8'
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    filesNotMatching("**/*.zip") {
        expand props
    }
}

shadowJar {
    // 3. Groovy drops the parentheses for method calls like relocate
    relocate 'org.bstats', "${project.group}.integration.bstats" 
    archiveClassifier.set('')
}

build.dependsOn shadowJar