## ============================================================================================= #
#   ██████╗  █████╗ ██╗   ██╗███╗   ██╗██╗ ██████╗ ██╗  ██╗████████╗██████╗ ██╗   ██╗██████╗    #
#   ██╔══██╗██╔══██╗╚██╗ ██╔╝████╗  ██║██║██╔════╝ ██║  ██║╚══██╔══╝██╔══██╗██║   ██║██╔══██╗   #
#   ██║  ██║███████║ ╚████╔╝ ██╔██╗ ██║██║██║  ███╗███████║   ██║   ██████╔╝██║   ██║██████╔╝   #
#   ██║  ██║██╔══██║  ╚██╔╝  ██║╚██╗██║██║██║   ██║██╔══██║   ██║   ██╔═══╝ ╚██╗ ██╔╝██╔═══╝    #
#   ██████╔╝██║  ██║   ██║   ██║ ╚████║██║╚██████╔╝██║  ██║   ██║   ██║      ╚████╔╝ ██║        #
#   ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝       ╚═══╝  ╚═╝        #
# ============================================================================================= #

# Language (en)
language: en

# Worlds configurations
worlds:
    world:
        enabled: true