name: DayNightPvP
version: '1.2.0.3'
main: com.needkg.daynightpvp.DayNightPvP
api-version: '1.18'
softdepend: [PlaceholderAPI, GriefPrevention, Vault]
commands:
  daynightpvp:
    description: "Open the gui."
    aliases: [ dnp ]