name: DayNightPvP
version: '1.2.0'
main: com.needkg.daynightpvp.DayNightPvP
api-version: '1.20'
softdepend: [PlaceholderAPI, GriefPrevention]
commands:
  daynightpvp:
    description: "Show all commands."
    aliases: [ dnp ]
  new: